name: Create Tag and Publish Docker Image

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: write
  packages: write

jobs:
  create-tag-and-publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create new tag
        id: create_tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          NEW_TAG=$(echo $LAST_TAG | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          
          # Check if the tag already exists
          if git rev-parse $NEW_TAG >/dev/null 2>&1; then
            echo "Tag $NEW_TAG already exists. Incrementing..."
            NEW_TAG=$(echo $NEW_TAG | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          fi
          
          git tag $NEW_TAG
          git push origin $NEW_TAG || echo "Failed to push tag $NEW_TAG. It might already exist remotely."
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Docker image name
        id: prep
        run: |
          IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.prep.outputs.IMAGE_NAME }}:latest
            ghcr.io/${{ steps.prep.outputs.IMAGE_NAME }}:${{ steps.create_tag.outputs.NEW_TAG }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
